purge_dir: "../data/PURGE"
output_base: "../models/${reward.type}"
forget_words_file: "${paths.purge_dir}/${entity.target}/${entity.forget_words_filename}"
forget_dataset_file: "${paths.purge_dir}/${entity.target}/${entity.forget_dataset_filename}"
output_dir: "${paths.output_base}/${model.name}-${entity.target}-${reward.type}"